---
# Project information
site_name: Networking Best Practices
site_url: https://aws.github.io/aws/aws-networking-best-practices/
site_description: >-
  AWS Networking Architecture guidance and best practices by the AWS user
  community, vetted by AWS Networking Specialist.

# Repository
repo_name: "Github Repo"
repo_url: https://github.com/aws/aws-networking-best-practices/
docs_dir: content
edit_uri: edit/main/content/

# Copyright
copyright: >
  <a href="https://aws.amazon.com/privacy/" target="_blank">Privacy</a> |
  <a href="https://aws.amazon.com/accessibility/" target="_blank">Accessibility</a> |
  <a href="https://aws.amazon.com/terms/" target="_blank">Site Terms</a> |
  <a href="#__consent">Cookie Preferences </a> |
  &copy; 2025, Amazon Web Services, Inc. or its affiliates. All rights reserved.

# Configuration
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  features:
    - tabs
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - announce.dismiss
    - header.autohide
    - toc.follow
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.expand
    - navigation.path
    - navigation.footer

# Additional configuration
extra:
  generator: false
  analytics:
    provider: google
    property: G-ZCN9MVZ9P6
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by using our
            <a href="https://github.com/aws/aws-networking-best-practices/issues/new/choose"
            target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - abbr
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - pymdownx.blocks.caption

extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - git-committers:
      repository: aws/aws-networking-best-practices
      branch: main
      docs_path: content
  - social
  - search

# Watch additional directories
watch:
  - includes

# Page tree
nav:
  - Introduction:
      - index.md
      - How to contribute: community/contribute.md
      - Report a correction: community/report-a-correction.md
      - New best practice: community/new-best-practice.md
      - Making a pull request: community/making-a-pull-request.md
      - Philosophy: community/philosophy.md
      - Conventions: community/conventions.md
  - Networking Basics:
      - basics/index.md
      - AWS Prerequisites: basics/aws-prerequisites.md
      - Setting up your first VPC: basics/first-vpc.md
  - Connectivity within AWS:
      - internal-connectivity/index.md
      - Within the same Region: internal-connectivity/vpc-same-region.md
      - Across Regions: internal-connectivity/vpc-other-region.md
  - Connectivity to the Internet:
      - internet-connectivity/index.md
      - Egress Traffic: internet-connectivity/egress.md
      - Ingress Traffic: internet-connectivity/ingress.md
  - Connectivity to on-premises and multicloud:
      - hybrid-connectivity/index.md
      - Network to Network: hybrid-connectivity/network-to-network.md
      - Clients to Network: hybrid-connectivity/clients-to-network.md
      - Clients to Applications: hybrid-connectivity/clients-to-apps.md
  - Network Security:
      - security/index.md
      - Perimeter Controls: security/perimeter-inbound.md
      - Outbound Controls: security/outbound.md
      - Network Segmentation: security/segmentation.md
  - Monitoring, Logging & Observability:
      - monitoring-observability/index.md
      - Notifications: monitoring-observability/notifications.md
      - AWS Services: monitoring-observability/service-monitoring.md
      - Internal Traffic: monitoring-observability/internal-traffic.md
      - External Traffic: monitoring-observability/external-traffic.md
